export enum AuthStatuses {
    LOGIN_ERROR = 'LOGIN_ERROR',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_ERROR = 'REGISTER_ERROR',
    EMAIL_EXISTS = 'EMAIL_EXISTS',
    PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS',
    PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR',
}
